### ISSUE TITLE
What is the `x` means in the dataloader ?

### ISSUE THREAD

**Issue by jacksonchen1998** [afengen/Bayesian-Crowd-Counting-#1]
Hello @afengen 

In the file `regression_trainer.py`.

The datasets can be defined as below

```
self.datasets = {x: Crowd(os.path.join(args.data_dir, x),
                                  args.crop_size,
                                  args.downsample_ratio,
                                  args.is_gray, x) for x in ['train', 'val']}
```

What is the `x` means in front of `for`.

Where the x in  `x) for`

I haven't seen that `Crowd` has any argument can use this as input.

Since that the `Crowd` has be defined as below

```
class Crowd(data.Dataset):
    def __init__(self, root_path, crop_size,
                 downsample_ratio, is_gray=False,
                 method='train'):
```

Thanks

**Comment by afengen** [comment]
Sorry, I'm also a learner of this project, maybe you can ask a question via the link：https://github.com/ZhihengCV/Bayesian-Crowd-Counting

**Comment by jacksonchen1998** [comment]
> Sorry, I'm also a learner of this project, maybe you can ask a question via the link：https://github.com/ZhihengCV/Bayesian-Crowd-Counting

OK.
